# Generated by Django 6.1 on 2026-08-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=14, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_tramite', models.CharField(choices=[('NUEVO', 'Pasaporte Nuevo'), ('RENOVACION', 'Renovación'), ('REPOSICION', 'Reposición')], max_length=20)),
                ('sede_sertrami', models.CharField(max_length=50)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('comprobante_pago', models.FileField(upload_to='comprobantes/')),
                ('codigo_confirmacion', models.CharField(editable=False, max_length=15, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
